### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by TurKurT656** [navasmdc/PhoneTutorial#3]
when i import ur library from gradle this error happens to me:

Error:Execution failed for task ':app:dexDebug'.

> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
>     C:\ADTBundle\SDK\build-tools\21.1.2\dx.bat --dex --no-optimize --output C:\ADTBundle\StudioWorkspace\NoiseTel\app\build\intermediates\dex\debug --input-list=C:\ADTBundle\StudioWorkspace\NoiseTel\app\build\intermediates\tmp\dex\debug\inputList.txt
> Error Code:
>     2
> Output:
>     UNEXPECTED TOP-LEVEL EXCEPTION:
>     com.android.dex.DexException: Multiple dex files define Lcom/nineoldandroids/animation/Animator$AnimatorListener;
>         at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
>         at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
>         at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
>         at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
>         at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
>         at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
>         at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
>         at com.android.dx.command.dexer.Main.run(Main.java:246)
>         at com.android.dx.command.dexer.Main.main(Main.java:215)
>         at com.android.dx.command.Main.main(Main.java:106)

i think this happens because of conflicting ur nineoldandroid with my other libs(that i imported from other githubs)
i have other libs that uses nineoldandroid. but just when i import ur lib this happpens :|

**Comment by TurKurT656** [comment]
i cant use this awesome lib because of this error
does anyone else have this problem too?

**Comment by deathprogrammer** [comment]
@TurkurT656  This error caused by you import multiple `nineoldandroid` library. the `PhoneTutorial` library have a `nineoldandroid` on it self. and you import `nineoldandroid` again.

**Comment by TurKurT656** [comment]
@deathprogrammer The problem is that I didnt import nineoldandroid lib. but maybe the other libs that I imported to project contains nineoldandroid library. so how can i fix this?

**Comment by deathprogrammer** [comment]
1. Press Ctrl+Alt+Shift+S
2. In `Modules` select your app
3. Select `Dependencies` 
4. Remove the library that contain `nineoldandroid` in it.

**Comment by TurKurT656** [comment]
@deathprogrammer so i have to remove another lib that this lib work? 
that is not the solution because i want my other libraries.
